openapi: 3.0.0
info:
  contact:
    email: "test@test.com"
  description: This is the swagger file that goes with our server code
  version: 1.0.0
  title: Swagger ReST Article
paths:
  /people:
    get:
      operationId: people.read_all
      tags:
        - People
      summary: Read the entire list of people
      description: Read the list of people
      parameters:
        - name: length
          in: query
          description: Number of people to get from people
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: Offset from beginning of list where to start gathering people
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Successfully read people list operation
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    timestamp:
                      type: string
    post:
      operationId: people.create
      tags:
        - people
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: First name of person to create
                last_name:
                  type: string
                  description: Last name of person to create
        description: Person to create
        required: true
      responses:
        "201":
          description: Successfully created person in list
  "/people/{last_name}":
    get:
      operationId: people.read_one
      tags:
        - people
      summary: Read one person from the people list
      description: Read one person from the people list
      parameters:
        - name: last_name
          in: path
          description: Last name of the person to get from the list
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully read person from people list operation
          content:
            application/json:
              schema:
                properties:
                  first_name:
                    type: string
                  last_name:
                    type: string
                  timestamp:
                    type: string
    put:
      operationId: people.update
      tags:
        - people
      summary: Update a person in the people list
      description: Update a person in the people list
      parameters:
        - name: last_name
          in: path
          description: Last name of the person to update in the list
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
      responses:
        "200":
          description: Successfully updated person in people list
    delete:
      operationId: people.delete
      tags:
        - people
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: last_name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully deleted a person from people list
servers:
  - url: /api
